import type { ScoringResult } from '../rules/types'
import type { QueryAnalysis } from '../query'

interface ReportData {
  url: string
  query: string | null
  scoring: ScoringResult
  queryAnalysis: QueryAnalysis | null
  createdAt: Date
}

export function generateMarkdownReport(data: ReportData): string {
  const { url, query, scoring, queryAnalysis, createdAt } = data
  
  const lines: string[] = []
  
  // Header
  lines.push(`# AEO Audit Report`)
  lines.push('')
  lines.push(`**URL:** ${url}`)
  lines.push(`**Date:** ${createdAt.toISOString().split('T')[0]}`)
  if (query) {
    lines.push(`**Target Query:** ${query}`)
  }
  lines.push('')
  
  // Overall Score
  lines.push(`## Overall Score: ${scoring.overallScore}/100`)
  lines.push('')
  
  // Module Summary
  lines.push(`## Module Scores`)
  lines.push('')
  lines.push(`| Module | Score | Grade |`)
  lines.push(`|--------|-------|-------|`)
  for (const mod of scoring.modules) {
    lines.push(`| ${mod.id}. ${mod.name} | ${mod.earnedPoints}/${mod.maxPoints} | ${mod.grade} |`)
  }
  lines.push('')
  
  // Query Fit (if applicable)
  if (queryAnalysis) {
    lines.push(`## Query Fit Analysis`)
    lines.push('')
    lines.push(`**Query Fit Score:** ${queryAnalysis.queryFitScore}/100`)
    lines.push(`**Query Intent:** ${queryAnalysis.queryIntent}`)
    lines.push('')
    lines.push(`**Coverage:**`)
    lines.push(`- Title/H1 Match: ${queryAnalysis.coverage.titleMatch}%`)
    lines.push(`- Headings Match: ${queryAnalysis.coverage.headingsMatch}%`)
    lines.push(`- Content Match: ${queryAnalysis.coverage.contentMatch}%`)
    lines.push('')
    
    if (queryAnalysis.missingElements.length > 0) {
      lines.push(`**Missing Elements:**`)
      for (const el of queryAnalysis.missingElements) {
        lines.push(`- ${el}`)
      }
      lines.push('')
    }
    
    if (queryAnalysis.answerDraft) {
      lines.push(`**Draft Answer:**`)
      lines.push(`> ${queryAnalysis.answerDraft}`)
      lines.push('')
    }
    
    if (queryAnalysis.suggestedFaqs.length > 0) {
      lines.push(`**Suggested FAQs to Add:**`)
      for (const faq of queryAnalysis.suggestedFaqs) {
        lines.push(`- ${faq}`)
      }
      lines.push('')
    }
  }
  
  // Detailed Rules
  lines.push(`## Detailed Findings`)
  lines.push('')
  
  for (const mod of scoring.modules) {
    lines.push(`### ${mod.id}. ${mod.name} (${mod.earnedPoints}/${mod.maxPoints})`)
    lines.push('')
    
    for (const rule of mod.rules) {
      const icon = rule.status === 'pass' ? '✅' : rule.status === 'warn' ? '⚠️' : '❌'
      lines.push(`#### ${icon} ${rule.id}: ${rule.title}`)
      lines.push('')
      lines.push(`**Score:** ${rule.earnedPoints}/${rule.maxPoints} | **Status:** ${rule.status.toUpperCase()}`)
      lines.push('')
      lines.push(`**Why it matters:** ${rule.whyItMatters}`)
      lines.push('')
      
      if (rule.evidence.length > 0) {
        lines.push(`**Evidence:**`)
        for (const ev of rule.evidence) {
          lines.push(`- ${ev}`)
        }
        lines.push('')
      }
      
      lines.push(`**Recommendation:** ${rule.recommendation}`)
      lines.push('')
    }
  }
  
  // Footer
  lines.push('---')
  lines.push('*Generated by Jersey Proper AEO Analyzer*')
  
  return lines.join('\n')
}
